version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: library_db
    environment:
      POSTGRES_DB: ${DB_NAME:-library}
      POSTGRES_USER: ${DB_USER:-library}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-library}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${DB_USER:-library} -d ${DB_NAME:-library}"]
      interval: 5s
      timeout: 3s
      retries: 12

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-library}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-library}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-library}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      # Если используешь профиль:
      # SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  dbdata:
