server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # схему создаёт Flyway
    show-sql: true
  flyway:
    locations: classpath:db/migration

application:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    expirationMs: 3600000

app:
  cors:
    origins: "http://localhost:5173"